name: Bug/Error Report
description: Something broken with NoobTacoUI?
labels: ["bug"]
body:
  - type: dropdown
    id: wow_version
    attributes:
      label: What version(s) of WoW are you using?
      multiple: true
      options:
        - Retail
        - Classic
        - Classic Era
        - Hardcore Classic
        - All
    validations:
      required: true
  
  - type: input
    id: addon_version
    attributes:
      label: What version of NoobTacoUI-Media?
      description: You can find this in your addon list or in the .toc file
    validations:
      required: true
  
  - type: textarea
    id: problem_description
    attributes:
      label: What isn't working? What was supposed to happen?
      description: Describe the bug and what you expected to happen instead
    validations:
      required: true
  
  - type: textarea
    id: lua_errors
    attributes:
      label: Are you experiencing any lua errors?
      description: These appear when using the BugSack+BugGrabber addons, or enabling script errors with `/console scriptErrors 1`
      placeholder: Paste any lua error messages here
    validations:
      required: false
  
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: false
  
  - type: textarea
    id: additional_info
    attributes:
      label: Additional information
      description: Any other information that might be helpful (screenshots, other addons you're using, etc.)
    validations:
      required: false
